#Service part3
kubectl delete -f ts-ui-dashboard-Service.yaml
#Service part2-2
kubectl delete -f ts-voucher-service-Service.yaml
kubectl delete -f ts-verification-code-service-Service.yaml
kubectl delete -f ts-travel-service-Service.yaml
kubectl delete -f ts-travel-plan-service-Service.yaml
kubectl delete -f ts-travel2-service-Service.yaml
kubectl delete -f ts-train-service-Service.yaml
kubectl delete -f ts-ticketinfo-service-Service.yaml
kubectl delete -f ts-ticket-office-service-Service.yaml
kubectl delete -f ts-station-service-Service.yaml
kubectl delete -f ts-sso-service-Service.yaml
kubectl delete -f ts-security-service-Service.yaml
kubectl delete -f ts-seat-service-Service.yaml
kubectl delete -f ts-route-service-Service.yaml
kubectl delete -f ts-route-plan-service-Service.yaml
kubectl delete -f ts-register-service-Service.yaml
#Service part2-1
kubectl delete -f ts-rebook-service-Service.yaml
kubectl delete -f ts-price-service-Service.yaml
kubectl delete -f ts-preserve-service-Service.yaml
kubectl delete -f ts-preserve-other-service-Service.yaml
kubectl delete -f ts-payment-service-Service.yaml
kubectl delete -f ts-order-service-Service.yaml
kubectl delete -f ts-order-other-service-Service.yaml
kubectl delete -f ts-notification-service-Service.yaml
kubectl delete -f ts-news-service-Service.yaml
kubectl delete -f ts-login-service-Service.yaml
kubectl delete -f ts-inside-payment-service-Service.yaml
kubectl delete -f ts-food-service-Service.yaml
kubectl delete -f ts-food-map-service-Service.yaml
kubectl delete -f ts-execute-service-Service.yaml
kubectl delete -f ts-contacts-service-Service.yaml
kubectl delete -f ts-consign-service-Service.yaml
kubectl delete -f ts-consign-price-service-Service.yaml
kubectl delete -f ts-config-service-Service.yaml
kubectl delete -f ts-cancel-service-Service.yaml
kubectl delete -f ts-basic-service-Service.yaml
kubectl delete -f ts-assurance-service-Service.yaml
kubectl delete -f ts-admin-user-service-Service.yaml
kubectl delete -f ts-admin-travel-service-Service.yaml
kubectl delete -f ts-admin-route-service-Service.yaml
kubectl delete -f ts-admin-order-service-Service.yaml
kubectl delete -f ts-admin-basic-info-service-Service.yaml
#Service part1
kubectl delete -f ts-verification-code-mongo-Service.yaml
kubectl delete -f ts-food-mongo-Service.yaml
kubectl delete -f ts-consign-price-mongo-Service.yaml
kubectl delete -f ts-consign-mongo-Service.yaml
kubectl delete -f ts-food-map-mongo-Service.yaml
kubectl delete -f ts-voucher-mysql-Service.yaml
kubectl delete -f ts-ticket-office-mongo-Service.yaml
kubectl delete -f ts-assurance-mongo-Service.yaml
kubectl delete -f ts-payment-mongo-Service.yaml
kubectl delete -f ts-inside-payment-mongo-Service.yaml
kubectl delete -f ts-security-mongo-Service.yaml
kubectl delete -f ts-price-mongo-Service.yaml
kubectl delete -f ts-travel2-mongo-Service.yaml
kubectl delete -f ts-travel-mongo-Service.yaml
kubectl delete -f ts-train-mongo-Service.yaml
kubectl delete -f ts-station-mongo-Service.yaml
kubectl delete -f ts-config-mongo-Service.yaml
kubectl delete -f ts-order-other-mongo-Service.yaml
kubectl delete -f ts-order-mongo-Service.yaml
kubectl delete -f ts-contacts-mongo-Service.yaml
kubectl delete -f ts-route-mongo-Service.yaml
kubectl delete -f ts-account-mongo-Service.yaml
kubectl delete -f redis-Service.yaml
#Deployment part3
kubectl delete -f ts-ui-dashboard-Deployment.yaml
#Deployment part2-2
kubectl delete -f ts-voucher-service-Deployment.yaml
kubectl delete -f ts-verification-code-service-Deployment.yaml
kubectl delete -f ts-travel-service-Deployment.yaml
kubectl delete -f ts-travel-plan-service-Deployment.yaml
kubectl delete -f ts-travel2-service-Deployment.yaml
kubectl delete -f ts-train-service-Deployment.yaml
kubectl delete -f ts-ticketinfo-service-Deployment.yaml
kubectl delete -f ts-ticket-office-service-Deployment.yaml
kubectl delete -f ts-station-service-Deployment.yaml
kubectl delete -f ts-sso-service-Deployment.yaml
kubectl delete -f ts-security-service-Deployment.yaml
kubectl delete -f ts-seat-service-Deployment.yaml
kubectl delete -f ts-route-service-Deployment.yaml
kubectl delete -f ts-route-plan-service-Deployment.yaml
kubectl delete -f ts-register-service-Deployment.yaml
#Deployment part2-1
kubectl delete -f ts-rebook-service-Deployment.yaml
kubectl delete -f ts-price-service-Deployment.yaml
kubectl delete -f ts-preserve-service-Deployment.yaml
kubectl delete -f ts-preserve-other-service-Deployment.yaml
kubectl delete -f ts-payment-service-Deployment.yaml
kubectl delete -f ts-order-service-Deployment.yaml
kubectl delete -f ts-order-other-service-Deployment.yaml
kubectl delete -f ts-notification-service-Deployment.yaml
kubectl delete -f ts-news-service-Deployment.yaml
kubectl delete -f ts-login-service-Deployment.yaml
kubectl delete -f ts-inside-payment-service-Deployment.yaml
kubectl delete -f ts-food-service-Deployment.yaml
kubectl delete -f ts-food-map-service-Deployment.yaml
kubectl delete -f ts-execute-service-Deployment.yaml
kubectl delete -f ts-contacts-service-Deployment.yaml
kubectl delete -f ts-consign-service-Deployment.yaml
kubectl delete -f ts-consign-price-service-Deployment.yaml
kubectl delete -f ts-config-service-Deployment.yaml
kubectl delete -f ts-cancel-service-Deployment.yaml
kubectl delete -f ts-basic-service-Deployment.yaml
kubectl delete -f ts-assurance-service-Deployment.yaml
kubectl delete -f ts-admin-user-service-Deployment.yaml
kubectl delete -f ts-admin-travel-service-Deployment.yaml
kubectl delete -f ts-admin-route-service-Deployment.yaml
kubectl delete -f ts-admin-order-service-Deployment.yaml
kubectl delete -f ts-admin-basic-info-service-Deployment.yaml
#Deployment part1
kubectl delete -f ts-verification-code-mongo-Deployment.yaml
kubectl delete -f ts-food-mongo-Deployment.yaml
kubectl delete -f ts-consign-price-mongo-Deployment.yaml
kubectl delete -f ts-consign-mongo-Deployment.yaml
kubectl delete -f ts-food-map-mongo-Deployment.yaml
kubectl delete -f ts-voucher-mysql-Deployment.yaml
kubectl delete -f ts-ticket-office-mongo-Deployment.yaml
kubectl delete -f ts-assurance-mongo-Deployment.yaml
kubectl delete -f ts-payment-mongo-Deployment.yaml
kubectl delete -f ts-inside-payment-mongo-Deployment.yaml
kubectl delete -f ts-security-mongo-Deployment.yaml
kubectl delete -f ts-price-mongo-Deployment.yaml
kubectl delete -f ts-travel2-mongo-Deployment.yaml
kubectl delete -f ts-travel-mongo-Deployment.yaml
kubectl delete -f ts-train-mongo-Deployment.yaml
kubectl delete -f ts-station-mongo-Deployment.yaml
kubectl delete -f ts-config-mongo-Deployment.yaml
kubectl delete -f ts-order-other-mongo-Deployment.yaml
kubectl delete -f ts-order-mongo-Deployment.yaml
kubectl delete -f ts-contacts-mongo-Deployment.yaml
kubectl delete -f ts-route-mongo-Deployment.yaml
kubectl delete -f ts-account-mongo-Deployment.yaml
kubectl delete -f redis-Deployment.yaml
