apiVersion: v1
kind: Service
metadata:
  name: ts-assurance-service
  labels:
    app: ts-assurance-service
spec:
  selector:
    app: ts-assurance-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 18888
      targetPort: 18888