apiVersion: v1
kind: Service
metadata:
  name: ts-admin-route-service
  labels:
    app: ts-admin-route-service
spec:
  selector:
    app: ts-admin-route-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 16113
      targetPort: 16113