apiVersion: v1
kind: Service
metadata:
  name: ts-admin-user-service
  labels:
    app: ts-admin-user-service
spec:
  selector:
    app: ts-admin-user-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 16115
      targetPort: 16115