apiVersion: v1
kind: Service
metadata:
  name: ts-admin-travel-service
  labels:
    app: ts-admin-travel-service
spec:
  selector:
    app: ts-admin-travel-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 16114
      targetPort: 16114