apiVersion: v1
kind: Service
metadata:
  name: ts-admin-basic-info-service
  labels:
    app: ts-admin-basic-info-service
spec:
  selector:
    app: ts-admin-basic-info-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 18767
      targetPort: 18767