apiVersion: v1
kind: Service
metadata:
  name: ts-basic-service
  labels:
    app: ts-basic-service
spec:
  selector:
    app: ts-basic-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 15680
      targetPort: 15680