apiVersion: v1
kind: Service
metadata:
  name: ts-consign-price-mongo
  labels:
    app: ts-consign-price-mongo
spec:
  selector:
    app: ts-consign-price-mongo
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017