apiVersion: v1
kind: Service
metadata:
  name: ts-consign-service
  labels:
    app: ts-consign-service
spec:
  selector:
    app: ts-consign-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 16111
      targetPort: 16111