apiVersion: v1
kind: Service
metadata:
  name: ts-contacts-service
  labels:
    app: ts-contacts-service
spec:
  selector:
    app: ts-contacts-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 12347
      targetPort: 12347