apiVersion: v1
kind: Service
metadata:
  name: ts-consign-price-service
  labels:
    app: ts-consign-price-service
spec:
  selector:
    app: ts-consign-price-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 16110
      targetPort: 16110