apiVersion: v1
kind: Service
metadata:
  name: ts-config-service
  labels:
    app: ts-config-service
spec:
  selector:
    app: ts-config-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 15679
      targetPort: 15679