apiVersion: v1
kind: Service
metadata:
  name: ts-cancel-service
  labels:
    app: ts-cancel-service
spec:
  selector:
    app: ts-cancel-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 18885
      targetPort: 18885