apiVersion: v1
kind: Service
metadata:
  name: ts-execute-service
  labels:
    app: ts-execute-service
spec:
  selector:
    app: ts-execute-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 12386
      targetPort: 12386