apiVersion: v1
kind: Service
metadata:
  name: ts-food-service
  labels:
    app: ts-food-service
spec:
  selector:
    app: ts-food-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 18856
      targetPort: 18856