apiVersion: v1
kind: Service
metadata:
  name: ts-food-map-service
  labels:
    app: ts-food-map-service
spec:
  selector:
    app: ts-food-map-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 18855
      targetPort: 18855