apiVersion: v1
kind: Service
metadata:
  name: ts-inside-payment-service
  labels:
    app: ts-inside-payment-service
spec:
  selector:
    app: ts-inside-payment-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 18673
      targetPort: 18673