apiVersion: v1
kind: Service
metadata:
  name: ts-order-other-service
  labels:
    app: ts-order-other-service
spec:
  selector:
    app: ts-order-other-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 12032
      targetPort: 12032