apiVersion: v1
kind: Service
metadata:
  name: ts-payment-service
  labels:
    app: ts-payment-service
spec:
  selector:
    app: ts-payment-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 19001
      targetPort: 19001