apiVersion: v1
kind: Service
metadata:
  name: ts-price-service
  labels:
    app: ts-price-service
spec:
  selector:
    app: ts-price-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 16579
      targetPort: 16579