apiVersion: v1
kind: Service
metadata:
  name: ts-preserve-service
  labels:
    app: ts-preserve-service
spec:
  selector:
    app: ts-preserve-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 14568
      targetPort: 14568