apiVersion: v1
kind: Service
metadata:
  name: ts-payment-mongo
  labels:
    app: ts-payment-mongo
spec:
  ports:
    - port: 27017
  selector:
    app: ts-payment-mongo
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017