apiVersion: v1
kind: Service
metadata:
  name: ts-preserve-other-service
  labels:
    app: ts-preserve-other-service
spec:
  selector:
    app: ts-preserve-other-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 14569
      targetPort: 14569