apiVersion: v1
kind: Service
metadata:
  name: ts-route-plan-service
  labels:
    app: ts-route-plan-service
spec:
  selector:
    app: ts-route-plan-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 14578
      targetPort: 14578