apiVersion: v1
kind: Service
metadata:
  name: ts-rebook-service
  labels:
    app: ts-rebook-service
spec:
  selector:
    app: ts-rebook-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 18886
      targetPort: 18886