apiVersion: v1
kind: Service
metadata:
  name: ts-route-service
  labels:
    app: ts-route-service
spec:
  selector:
    app: ts-route-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 11178
      targetPort: 11178