apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-station-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-station-mongo
      version: v1
  template:
    metadata:
      labels:
        app: ts-station-mongo
        version: v1
    spec:
      containers:
      - name: ts-station-mongo
        image: mongo:3.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"