apiVersion: v1
kind: Service
metadata:
  name: ts-seat-service
  labels:
    app: ts-seat-service
spec:
  selector:
    app: ts-seat-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 18898
      targetPort: 18898