apiVersion: v1
kind: Service
metadata:
  name: ts-sso-service
  labels:
    app: ts-sso-service
spec:
  #type: NodePort
  #ports:
  #  - port: 12349
  #    nodePort: 30003
  selector:
    app: ts-sso-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 12349
      targetPort: 12349