apiVersion: v1
kind: Service
metadata:
  name: ts-station-service
  labels:
    app: ts-station-service
spec:
  selector:
    app: ts-station-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 12345
      targetPort: 12345