apiVersion: v1
kind: Service
metadata:
  name: ts-security-service
  labels:
    app: ts-security-service
spec:
  selector:
    app: ts-security-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 11188
      targetPort: 11188