apiVersion: v1
kind: Service
metadata:
  name: ts-ticketinfo-service
  labels:
    app: ts-ticketinfo-service
spec:
  selector:
    app: ts-ticketinfo-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 15681
      targetPort: 15681