apiVersion: v1
kind: Service
metadata:
  name: ts-travel-service
  labels:
    app: ts-travel-service
spec:
  selector:
    app: ts-travel-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 12346
      targetPort: 12346