apiVersion: v1
kind: Service
metadata:
  name: ts-train-service
  labels:
    app: ts-train-service
spec:
  selector:
    app: ts-train-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 14567
      targetPort: 14567