apiVersion: v1
kind: Service
metadata:
  name: ts-travel-plan-service
  labels:
    app: ts-travel-plan-service
spec:
  selector:
    app: ts-travel-plan-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 14322
      targetPort: 14322