apiVersion: v1
kind: Service
metadata:
  name: ts-ticket-office-service
  labels:
    app: ts-ticket-office-service
spec:
  selector:
    app: ts-ticket-office-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 16108
      targetPort: 16108