apiVersion: v1
kind: Service
metadata:
  name: ts-travel2-service
  labels:
    app: ts-travel2-service
spec:
  selector:
    app: ts-travel2-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 16346
      targetPort: 16346