apiVersion: v1
kind: Service
metadata:
  name: ts-voucher-service
  labels:
    app: ts-voucher-service
spec:
  selector:
    app: ts-voucher-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 16101
      targetPort: 16101