apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-voucher-service
  labels:
    app: ts-voucher-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-voucher-service
      version: v1
  template:
    metadata:
      labels:
        app: ts-voucher-service
        version: v1
    spec:
      containers:
      - name: ts-voucher-service
        image: swlove2024/ts-voucher-service
        imagePullPolicy: Always
        ports:
        - containerPort: 16101
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"