apiVersion: v1
kind: Service
metadata:
  name: ts-verification-code-service
  labels:
    app: ts-verification-code-service
spec:
  selector:
    app: ts-verification-code-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 15678
      targetPort: 15678