apiVersion: v1
kind: Service
metadata:
  name: ts-register-service
  labels:
    app: ts-register-service
spec:
  selector:
    app: ts-register-service
  type: ClusterIP  #NodePort
  ports:
    - protocol: TCP
      port: 12344
      targetPort: 12344
      #nodePort: 12344
---

apiVersion: v1
kind: Service
metadata:
  name: ts-route-plan-service
  labels:
    app: ts-route-plan-service
spec:
  selector:
    app: ts-route-plan-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 14578
      targetPort: 14578
      
---

apiVersion: v1
kind: Service
metadata:
  name: ts-route-service
  labels:
    app: ts-route-service
spec:
  selector:
    app: ts-route-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 11178
      targetPort: 11178 

---

apiVersion: v1
kind: Service
metadata:
  name: ts-seat-service
  labels:
    app: ts-seat-service
spec:
  selector:
    app: ts-seat-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 18898
      targetPort: 18898 
---

apiVersion: v1
kind: Service
metadata:
  name: ts-security-service
  labels:
    app: ts-security-service
spec:
  selector:
    app: ts-security-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 11188
      targetPort: 11188 
---

apiVersion: v1
kind: Service
metadata:
  name: ts-sso-service
  labels:
    app: ts-sso-service
spec:
  #type: NodePort
  #ports:
  #  - port: 12349
  #    nodePort: 30003
  selector:
    app: ts-sso-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 12349
      targetPort: 12349 
---

apiVersion: v1
kind: Service
metadata:
  name: ts-station-service
  labels:
    app: ts-station-service
spec:
  selector:
    app: ts-station-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 12345
      targetPort: 12345 
  
---

apiVersion: v1
kind: Service
metadata:
  name: ts-ticket-office-service
  labels:
    app: ts-ticket-office-service
spec:
  selector:
    app: ts-ticket-office-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 16108
      targetPort: 16108 
  
---

apiVersion: v1
kind: Service
metadata:
  name: ts-ticketinfo-service
  labels:
    app: ts-ticketinfo-service
spec:
  selector:
    app: ts-ticketinfo-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 15681
      targetPort: 15681 
---

apiVersion: v1
kind: Service
metadata:
  name: ts-train-service
  labels:
    app: ts-train-service
spec:
  selector:
    app: ts-train-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 14567
      targetPort: 14567 

---

apiVersion: v1
kind: Service
metadata:
  name: ts-travel2-service
  labels:
    app: ts-travel2-service
spec:
  selector:
    app: ts-travel2-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 16346
      targetPort: 16346

---

apiVersion: v1
kind: Service
metadata:
  name: ts-travel-plan-service
  labels:
    app: ts-travel-plan-service
spec:
  selector:
    app: ts-travel-plan-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 14322
      targetPort: 14322
---

apiVersion: v1
kind: Service
metadata:
  name: ts-travel-service
  labels:
    app: ts-travel-service
spec:
  selector:
    app: ts-travel-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 12346
      targetPort: 12346

---

apiVersion: v1
kind: Service
metadata:
  name: ts-verification-code-service
  labels:
    app: ts-verification-code-service
spec:
  selector:
    app: ts-verification-code-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 15678
      targetPort: 15678


---

apiVersion: v1
kind: Service
metadata:
  name: ts-voucher-service
  labels:
    app: ts-voucher-service
spec:
  selector:
    app: ts-voucher-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 16101
      targetPort: 16101
