apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-{{.Iteration}}-{{.Replica}}
  namespace: bookinfo-test
  labels:
    app: details
    version: v1
    kube-burner-job: {{.JobName}}
    kube-burner-uuid: {{.UUID}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
      version: v1
  template:
    metadata:
      labels:
        app: details
        version: v1
    spec:
      containers:
      - name: details
        image: {{.containerImage}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        command:
        - sh
        - -c
        - |
          echo "[TIMING_DETAILS] container_start_ms:$(date +%s%3N)"
          ruby /opt/microservices/details.rb 9080
---
apiVersion: v1
kind: Service
metadata:
  name: details-{{.Iteration}}-{{.Replica}}
  namespace: bookinfo-test
  labels:
    app: details
    service: details
    kube-burner-job: {{.JobName}}
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: details
