apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage-{{.Iteration}}-{{.Replica}}
  namespace: bookinfo-test
  labels:
    app: productpage
    version: v1
    kube-burner-job: {{.JobName}}
    kube-burner-uuid: {{.UUID}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: v1
  template:
    metadata:
      labels:
        app: productpage
        version: v1
    spec:
      containers:
      - name: productpage
        image: {{.containerImage}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        # details/ratings와 동일한 command 방식 사용
        command:
        - sh
        - -c
        - |
          echo "[TIMING_PRODUCTPAGE] container_start_ms:$(date +%s%3N)"
          python /opt/microservices/productpage.py 9080
---
apiVersion: v1
kind: Service
metadata:
  name: productpage-{{.Iteration}}-{{.Replica}}
  namespace: bookinfo-test
  labels:
    app: productpage
    service: productpage
    kube-burner-job: {{.JobName}}
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: productpage
