apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-ui-dashboard
  labels:
    app: ts-ui-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-ui-dashboard
  template:
    metadata:
      labels:
        app: ts-ui-dashboard
        #version: v1
    spec:
      containers:
      - name: ts-ui-dashboard
        image: swlove2024/ts-ui-dashboard
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
